DROP TABLE IF EXISTS GoalActivities;
DROP TABLE IF EXISTS Goal;
DROP TABLE IF EXISTS ActivityLog;
DROP TABLE IF EXISTS Activity;

CREATE TABLE Activity(
Id				INTEGER PRIMARY KEY AUTOINCREMENT,
Name			TEXT NOT NULL UNIQUE,
ExpectedDurations INTEGER NOT NULL,
Description		TEXT NOT NULL,
Type			INTEGER NOT NULL,
CreatedAt		INTEGER NOT NULL,
HexColor    INTEGER NOT NULL
);

CREATE TABLE ActivityLog(
Id				INTEGER PRIMARY KEY AUTOINCREMENT,
Duration		INTEGER NOT NULL,
Description		TEXT,
Rating			INTEGER,
CreatedAt		INTEGER NOT NULL,
ActivityId		INTEGER NOT NULL,

FOREIGN KEY (ActivityId) REFERENCES Activity (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Goal(
Id				INTEGER PRIMARY KEY AUTOINCREMENT,
Name			TEXT NOT NULL UNIQUE,
CompletionWeight INTEGER NOT NULL,
Description TEXT NOT NULL,
CreatedAt		INTEGER NOT NULL,
ExpectedFinish	INTEGER,
Finished		INTEGER,
Type			INTEGER,
Percentage		REAL,
HexColor    INTEGER NOT NULL
);

CREATE TABLE GoalActivityRelation(
Id				INTEGER PRIMARY KEY AUTOINCREMENT,
GoalId			INTEGER,
ActivityId		INTEGER,
Weight INTEGER NOT NULL,

FOREIGN KEY (ActivityId) REFERENCES Activity (Id) ON DELETE CASCADE ON UPDATE NO ACTION,
FOREIGN KEY (GoalId) REFERENCES Goal (Id) ON DELETE CASCADE ON UPDATE NO ACTION
);